### ISSUE TITLE
Setting metadata Loops the filter run 7 times

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#15]
Hi, I'm testing the a metadata filter and I notice that the filter code is triggered 7 times.

```markdown
---
title: 'My Title'
author: John Doe
...
Minimal **example**.  
```

```ruby
#!/usr/bin/env ruby
require 'paru/filter'

testkey = 'author'

Paru::Filter.run do
  if metadata.has_key?(testkey)
    nau = nil
    au = metadata[testkey]
    if au.is_a?(String)
        warn "It's a string"
        nau = [Hash["name" => au]]
    elsif au.is_a?(Array)
        warn "It's an array"
        if au[0].is_a?(String)
          nau = Array.new(au.length) {Hash.new}
          au.each_index {|i| nau[i] = Hash["name" => au[i]]}
        end
    elsif au.is_a?(Hash)
        warn "It's a hash"
    else
      warn "Who know's what it is?"
    end
    if not nau.nil?
      metadata[testkey] = nau
    end
  end
end
```

```bash
👉  pandoc -s -f markdown -t markdown -F testFilter test.md
It's a string
It's an array
It's an array
It's an array
It's an array
It's an array
It's an array
---
author:
- name: John Doe
title: My Title
---

Minimal **example**.
```

As you can see the `warn` output is 7 lines long. Using byebug, when the metadata on line 32 is set I see:

```
[26, 35] in /Users/ian/.dotfiles/pandoc/filters/noop2
   26:     elsif au.is_a?(Hash)
   27:         warn "It's a hash"
   28:     else
   29:       warn "Who know's what it is?"
   30:     end
   31:     if not nau.nil?
=> 32:       metadata[testkey] = nau
   33:     end
   34:   end
   35: end
(byebug) n

[96, 105] in /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5f/lib/paru/filter/ast_manipulation.rb
    96:             #   tree
    97:             #
    98:             # @yield node
    99:             def each_depth_first(&block)
   100:                 yield self
=> 101:                 each {|child| child.each_depth_first(&block)} if has_children?
   102:             end
   103:
   104:         end
   105:     end
```

And this leads to another run through the filter. The longer the document, the more superfluous loops through the filter.

**Comment by htdebeer** [comment]
True. The filter is run for each and every one of the nodes in the pandoc AST. More nodes means running the filter more times. For the `with <selector> do ... end` actions this has to be done to a certain extent because any node could be a match. Furthermore, if this current `with` block cannot be a match, another one can be.

For metadata manipulation outside such a `with` block, you only want to run the action once and be done with it. I'll think about it some more, but at the moment I see three ways to improve this behavior:

1. Add an `exit_filter` method that exits the filter when it encounters it. In your example, you'd write it at the end of the filter and it would be run only once. 
2. Add the setup/teardown methods to a filter. In this case, you'd run your code in the setup and or teardown. It would still be running through all the nodes, though. So you'd want something like suggested in point 1 anyway.
3. Add a special "metadata filter" that does not do filtering, but only manipulates the metadata. 

What do you think about these suggestions?

**Comment by iandol** [comment]
Option 1 seems simplest — couldn't you just use the `return` keyword and overload it (or whatever the term is in Ruby) so that it can work in this case?

**Comment by htdebeer** [comment]
That is a great idea! I'll investigate if the "return" statement can be overridden, although I doubt it. Only operators can be overridden in Ruby, afaik. But there is the `Process#exit` method one can use to kill a process/application, so using plain `exit` in a filter might be a good alternative to overriding the return statement.

**Comment by htdebeer** [comment]
I added a `stop!` method which immediately stops a filter and outputs the document as it is at that point in time. For example

    Paru::Filter.run do
            metadata['title'] = "Say hello to the world"
            metadata['date'] = "12-12-1812"
            metadata['author'] = "Huub de Beer"
            stop!
    end

This filter will be run only once. It is in the latest version 0.2.5f.

I prefer `stop` over `exit` because exit has a different connotation: exit the program without a care for the current state. Stop on the other hand signals to stop _running_ the filter gracefully and continue to output the result of the stopped filter.

**Comment by iandol** [comment]
Great, thanks Huub!

stop!
