### ISSUE TITLE
convert issue on Windows (?)

### ISSUE THREAD

**Issue by xbelanch** [htdebeer/paru#19]
I don't know if this is a bug or not but testing the "hello world" test script on Windows 10 it complains with this:

pandoc: \
: openFile: invalid argument (Invalid argument)

Ruby version: ruby 2.4.0p0 (2016-12-24 revision 57164) [i386-mingw32]

Tell me if you need more information.

Thanks in advance!

**Comment by htdebeer** [comment]
I do not use Windows myself, so I cannot reproduce this easily. But if it is breaking on `examples/hello_world.rb` something is amis with running pandoc from ruby. 

Question, does running the `info` method work?

```
huub@study:~/Projects/paru$ irb
irb(main):001:0> require 'paru/pandoc'
=> true
irb(main):002:0> Paru::Pandoc.info
=> {:version=>"1.19.2.1", :data_dir=>"/home/huub/.pandoc"}
```

If so, does the following work as well?

```
irb(main):003:0> Paru::Pandoc.new do
irb(main):004:1* from "markdown"
irb(main):005:1> to "html"
irb(main):006:1> end << "Hello *world*"
=> "<p>Hello <em>world</em></p>\n"
```

If not, can you try the following and report the results back:

```
irb(main):001:0> output = ''
=> ""
irb(main):002:0> IO.popen('pandoc --version', 'r+') do |p|
irb(main):003:1*    p.close_write
irb(main):004:1>   output << p.read
irb(main):005:1> end
=> "pandoc 1.19.2.1\nCompiled with pandoc-types 1.17.0.5, texmath 0.9.4, skylighting 0.1.1.5\nDefault user data directory: /home/huub/.pandoc\nCopyright (C) 2006-2016 John MacFarlane\nWeb:  http://pandoc.org\nThis is free software; see the source for copying conditions.\nThere is no warranty, not even for merchantability or fitness\nfor a particular purpose.\n"
```

**Comment by htdebeer** [comment]
Nice to hear your voice!

Okay. It seems that pandoc runs fine, as well as running pandoc without any input (as in the `info` method). However, the problem seems to be with sending input to pandoc on windows. For some other issue I added the "shellwords" library to properly escape the pandoc command I run in paru. This might be causing the issue. Would you mind trying entering the following in IRB:

```
irb(main):008:0> require 'paru/pandoc'
=> true
irb(main):009:0> converter = Paru::Pandoc.new do
irb(main):010:1*   from "markdown"
irb(main):011:1>   to "html"
irb(main):012:1> end
=> #<Paru::Pandoc:0x005635ef8467e8 @options={"from"=>"markdown", "to"=>"html"}>
irb(main):013:0> converter.to_command
=> "pandoc\t--from=markdown \\\n\t--to=html"
irb(main):014:0> converter.convert "hello _world_"
=> "<p>hello <em>world</em></p>\n"
```

The `converter.to_command` method prints the command paru uses to invoke pandoc. Can you execute that command on the command line in windows? On Linux I have to run that like so:

```
echo "hello _world_" | `echo -e "pandoc\t--from=markdown \\\n\t--to=html"
```

All the `\t`, `\\`, `\n` characters format the invocation string, but it might be messing with the operation on Windows somehow. Looking on the internet, this seems to be an issue indeed.

I adapted the code to not escape anything on windows. Would you mind testing paru version 0.2.5.1.a? You can find it [here](https://github.com/htdebeer/paru/blob/master/releases/paru-0.2.5.1a.gem).

**Comment by xbelanch** [comment]
Bad news :( https://youtu.be/TdMt5WHANz4

**Comment by htdebeer** [comment]
I see. The good news is, the shellwords addition wasn't the problem. The bad news is, it still doesn't work. Just for my curiosity: has paru ever worked on windows?

Anyway, I'll download a Windows VM and I will try to replicate the issue so I can fix it.

**Comment by xbelanch** [comment]
That was my first time to play with Paru on Windows. Let me test it on another machine: I have an odd feeling that maybe it's my "ruby installation" or something weird around it...

**Comment by xbelanch** [comment]
Good news: I "downgraded" Ruby to 2.3.3p222 and it works! Sounds insane and crazy but it's true :-S I understand that some is living inside 2.4 version. Speechless...

**Comment by htdebeer** [comment]
Awesome! Then I'll revert the change with the shellwords and call it a fix :-)
