### ISSUE TITLE
Paru documentation

### ISSUE THREAD

**Issue by xbelanch** [htdebeer/paru#6]
I found this Paru documentation (https://heerdebeer.org/Software/markdown/paru/#frequently-asked-questions) very heplful but I'm stuck at the time of extract the metadata from the markdown file (section 2.1)

$ ./pandoc2yaml.rb:32:in `values_at': no implicit conversion of String into Integer (TypeError)

I googled a bit (https://stackoverflow.com/questions/20790499/no-implicit-conversion-of-string-into-integer-typeerror) but I did'nt obtain a way to workaround that issue.

**Comment by htdebeer** [comment]
In response to your issue, I have investigated the issue a bit. I did find some problems with the pandoc2yaml executable, which I have fixed in paru version 0.2.4.5. Please update your paru installation to that version and try again.

If the problem persists, could you also supply a minimal markdown file with YAML metadata which gives the error you mentioned? Then I can investigate further.

**Comment by xbelanch** [comment]
I updated paru to 0.2.4.5 but the issue still persists:

./second_script.rb test.md 
/home/user/paru_test_zone/pandoc2yaml.rb:32:in `values_at': no implicit conversion of String into Integer (TypeError)
	from /home/user/paru_test_zone/pandoc2yaml.rb:32:in `extract_metadata'
	from ./second_script.rb:14:in `<main>'

Additional info: gem local --list

*** LOCAL GEMS ***

bigdecimal (1.3.2, default: 1.3.0)
bundler (1.15.0)
bundler-unload (1.0.2)
did_you_mean (1.1.2, 1.1.0)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (default: 0.4.6)
json (default: 2.0.2)
minitest (5.10.2, 5.10.1)
net-telnet (0.1.1)
openssl (2.0.3, default: 2.0.2)
paru (0.2.4.5)
power_assert (1.0.2, 0.4.1)
psych (2.2.4, default: 2.2.2)
rack (2.0.3, 1.6.8)
rake (12.0.0)
rdoc (5.1.0, default: 5.0.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (3.2.4, 3.2.3)
vienna (0.4.1)
xmlrpc (0.3.0, 0.2.1)

Ruby version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

On the other hand... if I try to test a simple filter like the 'add_today.rb' I obtain a similar issue:

pandoc -s test.md -o test2.md --filter ./add_today.rb
/home/xbelanch/.rvm/gems/ruby-2.4.0/gems/paru-0.2.4.5/lib/paru/filter/document.rb:54:in `values_at': no implicit conversion of String into Integer (TypeError)
	from /home/xbelanch/.rvm/gems/ruby-2.4.0/gems/paru-0.2.4.5/lib/paru/filter/document.rb:54:in `from_JSON'
	from /home/xbelanch/.rvm/gems/ruby-2.4.0/gems/paru-0.2.4.5/lib/paru/filter.rb:237:in `document'
	from /home/xbelanch/.rvm/gems/ruby-2.4.0/gems/paru-0.2.4.5/lib/paru/filter.rb:264:in `filter'
	from /home/xbelanch/.rvm/gems/ruby-2.4.0/gems/paru-0.2.4.5/lib/paru/filter.rb:228:in `run'
	from ./add_today.rb:6:in `<main>'
pandoc: Error running filter ./add_today.rb


[test.txt](https://github.com/htdebeer/paru/files/1037388/test.txt)

**Comment by htdebeer** [comment]
I have trouble reproducing this issue. If I run the executable `pandoc2yaml.rb` that is installed in `/usr/local/bin/` on my machine, or using the one in the `bin` directory in paru's repository, I get back the YAML metadata. 

Similarly, if I run `pandoc -s test.txt -o test2.md --filter paru/examples/filters/add_today.rb`, I get an test2.md with the date mixed in.

I did change the pandoc2yaml.rb script yesterday, though. I separated the script from the actual code that does the conversion. That latter module has moved to `lib/paru/pandoc2yaml.rb`. I use it in `pandoc2yaml.rb` as follows:

    require 'paru/pandoc2yaml'
    ...
    document = File.expand_path input_document
    yaml = Paru::Pandoc2Yaml.extract_metadata(document)

But looking at your stack trace, that does not seem to be the issue. I see that the problem is reported in `lib/paru/filter/document.rb`, right after parsing the JSON the add_today.rb filter gets from pandoc. It should parse that JSON into a Hash, but the `values_at` method seems to try to convert the string for version and metadata into an integer.

If you parse the JSON output by pandoc, do you get a Hash or an Array? For the `values_at` method on an Array does expect integers.

What version of pandoc are you using? I am using pandoc 1.19.2.1 and paru 0.2.x is not compatible with pandoc < 1.18 due to an API change in the pandoc filters.

**Comment by xbelanch** [comment]
My bad: I was using an old version of Pandoc (1.6.x) -I wasn't aware of this detail!- I upgraded to 1.9.2.21 and it works well. Maybe it will be useful some checking pandoc version before Paru does anything (most of linux distros offering old versions in their repositories of Pandoc). Now it's time to play with filters!

Very thanks for your help and time!

**Comment by htdebeer** [comment]
Checking the version might be a good idea! I'll look into that.

Thanks for the suggestion.
