### ISSUE TITLE
Error while running on heroku

### ISSUE THREAD

**Issue by sudeeptarlekar** [htdebeer/paru#75]
Trying to install application on heroku with custom filter in the rails app. `pandoc -v` gives following output
```
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /app/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

but while running the server getting error
```
Most likely cause: Paru expects a pandoc installation that has been
compiled with pandoc-types >= 1.22. You can
check which pandoc-types have been compiled with your pandoc installation by
running `pandoc -v`.
```

Any guess what I am might be missing or doing something wrong here?

**Comment by htdebeer** [comment]
No. I need a reproducible scenario to investigate your issue. Can you supply a minimal but complete scenario where this happens? In particular, I am interested in the input file and the filter(s) you used, as well as the actual pandoc command or paru converter you run.

Also, looking in paru's current code, there should be more to this error message: it should also show the original error message that caused this message to be shown. Do you have any more output after "...running \`pandoc - v\`."?

**Comment by sudeeptarlekar** [comment]
So this is parser I have added 

```
# ap/lib/pandoc/pparser.rb

require 'paru/pandoc'
require 'paru/filter'

class Pandoc::Parser
  attr_accessor :converter, :content

  def initialize(content)
    @converter = Paru::Pandoc.new do
      from "markdown+tex_math_single_backslash"
      to "html5+smart"
      filter Rails.root.join('app/lib/pandoc_filters', 'block_filter.rb').to_s
      filter 'pandoc-sidenote'
    end
    @content = content
  end

  def convert
    @converter.convert content
  end
end
```

And this is custom filter definition I have

```
# app/lib/pandoc_filters/block_filter.rb
# frozen_string_literal: true

require 'paru/filter'
require 'paru/pandoc'

require_relative '../lti_tool'

def learn_lti(attrs)
  launch_data = LTITool.new(
    url: attrs['launch_url'],
    consumer_key: attrs['consumer_key'],
    consumer_secret: attrs['consumer_secret']
  ).create_tool_consumer.generate_launch_data

  form = "<form action='#{attrs['launch_url']}' method='POST'>"
  form.concat(
    launch_data.map do |key, value|
      "<input type=\'hidden\' name=\'#{key}\' value=\'#{value}\' id=\'#{key}\'/>"
    end.join('')
  )
  form.concat("<input type='submit' value='Launch Video'/></form>")
  Paru::PandocFilter::RawBlock.new([
    'html',
    form
  ])
end

Paru::Filter.run do
  with 'Div.lti_tool' do |div|
    attrs = div.inner_markdown.split(%r{;[\s\n]}).map { |s| s.split('=') }.to_h
    div.parent.replace(div, learn_lti(attrs))
  end
end
```

And when I try to start a server on heroku using following command
```
bundle exec puma -p 29151 -C ./config/puma.rb
```

**Comment by sudeeptarlekar** [comment]
I think I missed `pandoc-sidenote` filter on heroku, my bad again.

**Comment by htdebeer** [comment]
I have trouble reproducing your issue because I've no idea what the actual input markdown looks like, nor what sort of output your LTI tool produces in the filter. I've tried to come up with the following minimal example, but I've no idea how close this is to your actual situation:

-   `test.md`, the input markdown file:
    
    ```markdown
    The next div will be replaced by a FORM element.

    :::: {.lti_tool}
    key1="hello" ; key2=45
    ::::
    ```

-   `mock-block-filter.rb`, a simplified version of your filter that doesn't use your LTI tool:

    ```ruby
    #!/usr/bin/env ruby
    require 'paru/filter'

    def learn_lti(attrs)
        launch_data = attrs
        form = "<form action='https://example.com/action' method='POST'>"
        form.concat(
            launch_data.map do |key, value|
                "<input type=\'hidden\' name=\'#{key}\' value=\'#{value}\' id=\'#{key}\'/>"
            end.join('')
        )
        form.concat("<input type='submit' value='Launch Video'/></form>")
        Paru::PandocFilter::RawBlock.new([
            'html',
            form
        ])
    end

    Paru::Filter.run do
        with 'Div.lti_tool' do |div|
            attrs = div.inner_markdown.split(%r{;[\s\n]}).map { |s| s.split('=') }.to_h
            div.parent.replace(div, learn_lti(attrs))
        end
    end
    ```

-   The pandoc command to run this filter on that input file:

    ```bash
    pandoc --from markdown+tex_math_single_backslash --filter mock_block_filter.rb --to html5+smart test.md
    ````

This works without an error on my machine. However, I don't know what the actual data in your DIVs is, not what your LTI tool is doing.

Can you try to make and try a similar minimal example and run it from the commandline rather than via the paru converter and report back what happens? In particular, I am also interested to know if your LTI tool produces any content on standard out. Because if it does, that messes with pandoc's convention to use standard out to communicate between pandoc and filters.

The most likely cause of the original error you reported is having produced a document that's no longer a valid pandoc document. For example, because there's extra communication on standard out.

**Comment by sudeeptarlekar** [comment]
Thanks @htdebeer for looking into this.

As I mentioned `pandoc-sidenote` filter was not install on heroku and this is what causing the issue. After installing filter on heroku, was able to render content.

Closing for now
